# Generated by Django 6.0.2 on 2026-03-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='感想'),
        ),
    ]
